version: "3"
services:
  database:
    network_mode: host
    image: "mongo"
    container_name: "sharingconcerns-mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=sharingconcerns
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017-27019:27017-27019"

  server:
    network_mode: host
    image: node
    container_name: "sharingconcerns-server-container"
    working_dir: /usr/app/server
    volumes:
      - ./server:/usr/app/server
      # - /usr/app/server/node_modules
    command: npm start
    ports:
      - "8000:8000"
    depends_on:
      - database
  client:
    network_mode: host
    image: node
    container_name: "sharingconcerns-client-container"
    working_dir: /usr/app/client
    command: npm start
    volumes:
      - ./client:/usr/app/client
      # - /usr/app/client/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
