version: "3"
services:
  database:
    image: "mongo"
    container_name: "sharingconcerns-mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=sharingconcerns
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017-27019:27017-27019"
